//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : VenDB
	/// Data Source    : .\SQLEXPRESS
	/// Server Version : 14.00.1000
	/// </summary>
	public partial class VenDB : LinqToDB.Data.DataConnection
	{
		public ITable<Event> Events { get { return this.GetTable<Event>(); } }
		public ITable<Log>   Logs   { get { return this.GetTable<Log>(); } }

		public VenDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public VenDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table(Schema="dbo", Name="Events")]
	public partial class Event
	{
		[PrimaryKey, Identity   ] public int       Id               { get; set; } // int
		[Column,     NotNull    ] public string    VenID            { get; set; } // varchar(50)
		[Column,     NotNull    ] public string    VenName          { get; set; } // varchar(50)
		[Column,     NotNull    ] public int       VenNum           { get; set; } // int
		[Column,        Nullable] public string    IDEvent          { get; set; } // varchar(50)
		[Column,        Nullable] public DateTime? StartTime        { get; set; } // datetime
		[Column,        Nullable] public string    Duration         { get; set; } // varchar(50)
		[Column,        Nullable] public string    Status           { get; set; } // varchar(50)
		[Column,        Nullable] public string    OptState         { get; set; } // varchar(20)
		[Column,        Nullable] public string    MarketContext    { get; set; } // varchar(1000)
		[Column,        Nullable] public string    SignalType       { get; set; } // varchar(50)
		[Column,        Nullable] public string    CurrentValue     { get; set; } // varchar(1000)
		[Column,        Nullable] public string    VTNComment       { get; set; } // varchar(1000)
		[Column,        Nullable] public string    TestEvent        { get; set; } // varchar(1000)
		[Column,        Nullable] public string    ResponseRequired { get; set; } // varchar(1000)
		[Column,        Nullable] public DateTime? DateCreated      { get; set; } // datetime
	}

	[Table(Schema="dbo", Name="Logs")]
	public partial class Log
	{
		[Column(),               PrimaryKey,  Identity] public int       Id                  { get; set; } // int
		[Column(),               NotNull              ] public int       VenNum              { get; set; } // int
		[Column(),               NotNull              ] public string    VenID               { get; set; } // varchar(50)
		[Column(),               NotNull              ] public string    VenName             { get; set; } // varchar(50)
		[Column(),                  Nullable          ] public DateTime? Date                { get; set; } // datetime
		[Column("responseTime"),    Nullable          ] public decimal?  ResponseTime        { get; set; } // decimal(18, 0)
		[Column("requestType"),     Nullable          ] public string    RequestType         { get; set; } // varchar(50)
		[Column("responseType"),    Nullable          ] public string    ResponseType        { get; set; } // varchar(50)
		[Column(),                  Nullable          ] public int?      ResponseCode        { get; set; } // int
		[Column(),                  Nullable          ] public string    ResponseDescription { get; set; } // varchar(1000)
		[Column("requestXML"),      Nullable          ] public string    RequestXML          { get; set; } // varchar(1000)
		[Column("responseXML"),     Nullable          ] public string    ResponseXML         { get; set; } // varchar(1000)
		[Column(),                  Nullable          ] public DateTime? DateCreated         { get; set; } // datetime
		[Column(),                  Nullable          ] public string    Type                { get; set; } // varchar(50)
	}

	public static partial class TableExtensions
	{
		public static Event Find(this ITable<Event> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Log Find(this ITable<Log> table, int Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}

#pragma warning restore 1591
